# Service Config
image: __CONTAINER__
imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  apiPath: /api/legal/v1/
  readinessType: exec
  readinessProbeHttpPath: /api/legal/v1/_ah/liveness_check
  startupProbeHttpPath: /api/legal/v1/_ah/liveness_check
serviceParameters:
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/legal/legal-sns-topic-arn"
  objectType: "ssmparameter"
  objectAlias: legal-sns-topic-arn
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis/redisauthtoken"
  objectType: "secretsmanager"
  objectAlias: "CACHE_CLUSTER_KEY"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point"
  objectType: "ssmparameter"
  objectAlias: "CACHE_CLUSTER_ENDPOINT"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point-port"
  objectType: "ssmparameter"
  objectAlias: "CACHE_CLUSTER_PORT"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/mongodb/endpoint"
  objectType: "ssmparameter"
  objectAlias: "mongodb_host"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/mongodb/port"
  objectType: "ssmparameter"
  objectAlias: "mongodb_port"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/mongodb/credentials"
  objectType: "secretsmanager"
  objectAlias: "mongodb_credentials"
environmentVariables:
  - name: APPLICATION_PORT
    value: "{{ .Values.service.port }}"
  - name: AWS_REGION
    value: "{{ .Values.global.region }}"
  - name: ENVIRONMENT
    value: "{{ .Values.global.resourcePrefix }}"
  - name: JAVA_OPTS
    value: "-Xms50M -Xmx900M"
  - name: LOG_LEVEL
    value: "{{ default `INFO` .Values.global.logLevel }}"
  - name: SSM_ENABLED
    value: "True"
  - name: SSL_ENABLED
    value: "false"
  - name: ENTITLEMENTS_BASE_URL
    value: "http://os-entitlements:8080"
  - name: PARTITION_BASE_URL
    value: http://os-partition:8080
  - name: PARAMETER_MOUNT_PATH
    value: "/mnt/params"
  - name: LEGAL_SERVICE_REPOSITORY_IMPLEMENTATION
    value: "{{ default `dynamodb` .Values.global.coreDbProvider }}"
  - name: MONGODB_RETRY_WRITES
    value: "true"
  - name: MONGODB_WRITE_MODE
    value: "majority"
  - name: MONGODB_USE_SRV_ENDPOINT
    value: "true"
  - name: MONGODB_ENABLE_TLS
    value: "false"
podAnnotations: {}

# Resource Config
maxConnections: 200
replicaCount: 1
resources:
  limits:
    memory: 900M
  requests:
    cpu: 500m
    memory: 900M
autoscaling:
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90
  coolDownPeriod: 120
  ServiceRequestCountThreshold: 35
  ServiceRequestDurationAverage: 500

# Security Config
serviceAccountRole: arn:aws:iam::{{ .Values.global.accountID }}:role/{{ .Values.global.resourcePrefix }}-{{ include "common.name" . }}
cors:
  maxAge: "60m"
  allowCredentials: true
  allowMethods: 
    - POST
    - GET
    - PUT
    - DELETE
  allowHeaders:
    - Authorization
    - Data-Partition-Id
    - Correlation-Id
    - Content-Type
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
allowedPrincipals:
  - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
  - cluster.local/ns/{{ .Release.Namespace }}/sa/compliance-queue-trigger
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-policy
  - cluster.local/ns/{{ .Release.Namespace }}/sa/opa-agent
  - cluster.local/ns/{{ .Release.Namespace }}/sa/os-storage
  - cluster.local/ns/aws-binary-dms/sa/binary-dms
  - cluster.local/ns/osdu-airflow/sa/airflow-dag-upload
  - cluster.local/ns/osdu-airflow/sa/airflow-worker
  - cluster.local/ns/osdu-ingest/sa/os-data-workflow
  - cluster.local/ns/osdu-ingest/sa/os-ingestion-workflow
  - cluster.local/ns/osdu-seismic-ddms/sa/os-seismic-store
  - cluster.local/ns/osdu-well-delivery/sa/os-welldelivery
  - cluster.local/ns/osdu-wellbore-ddms/sa/os-wellbore-ddms
